/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendamclient
// Asset An asset is a single managed digital asset
type Asset struct {
	// The unique id of the asset
	AssetId string `json:"asset_id"`
	Kind Kind `json:"kind"`
	Version Version `json:"version"`
	File AssetFile `json:"file"`
	// additional assets/files associated with the asset
	Formats []Asset `json:"formats,omitempty"`
	// A list of metadata tags associated with the asset
	Tags []string `json:"tags,omitempty"`
	// Any user supplied metadata for the asset
	Metadata map[string]map[string]interface{} `json:"metadata,omitempty"`
}
