/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendamclient
// Kind The kind of media
type Kind string

// List of kind
const (
	IMAGE Kind = "image"
	VIDEO Kind = "video"
	AUDIO Kind = "audio"
	TEXT Kind = "text"
)
