/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendamclient
// AssetUpdate A limited view of an asset with only editable fields. Formats, tags, and metadata are merged with any existing values
type AssetUpdate struct {
	Kind Kind `json:"kind,omitempty"`
	File AssetFile `json:"file,omitempty"`
	// additional assets/files associated with the asset
	Formats []Asset `json:"formats,omitempty"`
	// A list of metadata tags/classifications associated with the asset
	Tags []string `json:"tags,omitempty"`
	// Any user supplied or extracted metadata for the asset
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
