/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendamclient
// Task a task to perform on an asset
type Task struct {
	// The name of the task
	Task string `json:"task,omitempty"`
	// An array of arguments to use for the task, if left empty will use the results of the previous task. must match the expected arguments for the requested task.
	Args []string `json:"args,omitempty"`
}
