/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendamclient
// ApiError struct for ApiError
type ApiError struct {
	// A HTTP status code applicable to this problem
	Code float32 `json:"code"`
	// A description of the error that occurred
	Message string `json:"message"`
}
