/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendamclient
// Job The state of a single job
type Job struct {
	// The unique id of the job
	Id string `json:"id"`
	// The state of the job
	State string `json:"state"`
	// The asset that this job is processing work for
	AssetId string `json:"asset_id"`
}
