/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendamclient
// AssetCreate The information required to start the workflow to create or update an asset
type AssetCreate struct {
	Url string `json:"url"`
	// The unique id of the asset
	AssetId string `json:"asset_id,omitempty"`
}
