/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendamclient
// JobCreate The task information for a workflow
type JobCreate struct {
	Tasks []Task `json:"tasks,omitempty"`
}
