/*
 * Open DAM API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package opendamclient
// AssetFile The file associated with an asset or format
type AssetFile struct {
	// the name of the file
	Name string `json:"name"`
	// A URL address to the file content
	Source string `json:"source"`
	// the http Content-Type used with the file
	ContentType string `json:"content_type"`
	// The size of the file in bytes
	Size float32 `json:"size"`
	// The width of the file
	Width float32 `json:"width,omitempty"`
	// The height of the file
	Height float32 `json:"height,omitempty"`
	// The duration of the file in seconds
	Duration float32 `json:"duration,omitempty"`
}
